name: CI
on: 
# События, которые запускают jobs
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
jobs:
# jobs запускаются параллельно, если не указана последовательность
    Cijob1:
        runs-on: ubuntu-latest
        container:
          image: node:18
        steps: 
            - uses: action/checkout@v4
              with:
                  sparse-checkout: |
                    workflows
            - name: install gcc
              run: sudo apt install gcc -y

            - name: build package
              run: |
                  ls -l 
                  dpkg-deb --build ./source/package    

          # Загрузка собранного пакета из этой джобы и передача его в следующую джобу
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: package
                path: source/package.deb

            - name: isntall package
              run: sudo apt-get install ./source/package.deb

            - name: test package
              run: buildpackage

    Cijob2:
      # В случае успеха первой джобы запустится выполнение данной джобы
          needs: [Cijob1]
          runs-on: ubuntu-latest
          steps:
              - name: doing smth
                run: uptime
       
          # Загрузка пакета из предыдущей джобы
              - name: Download artifact
                uses: actions/download-artifact@v4
                with:
                  name: package

              - name: a few jobs
                run: | 
                  ls -l
                  mkdir ${{env.directory}}
                  cd ${{env.directory}}
                  pwd
                  
              - name: isntall/test package
                run: | 
                  sudo apt-get install ./package.deb
                  echo " "
                  buildpackage
