name: CI
on: 
# События, которые запускают jobs
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
jobs:
# jobs запускаются параллельно, если не указана последовательность
    Cijob1:
        runs-on: ubuntu-latest
        container:
          image: node:18
        steps: 
            - uses: action/checkout@v4
              with:
                  sparse-checkout: |
                    workflows
            - name: installdeb
              run: |
                   sudo dpkg -i test1.dpb
                    sudo apt-get -f install


    Cijob2:
        runs-on: oracle-latest
        container:
          image: node:19
        steps: 
              - uses: action/checkout@v4
                with:
                  sparse-checkout: |
                    workflows
              - name: installrpm
                run: | 
                    sudo yum -y install yum-utils
                    sudo yum install -y test2.rpm
        
