name: CI
on: 
# События, которые запускают jobs
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
jobs:
# jobs запускаются параллельно, если не указана последовательность
    Cijob1:
        runs-on: ubuntu-latest
        container:
          image: node:18
        steps: 
            - uses: action/checkout@v4
            - name: installdeb
              run: |
                  curl -o file.dpb ссылка
                   sudo dpkg -i file.dpb
                    sudo apt-get -f install


    Cijob2:
        runs-on: oracle-latest
        container:
          image: node:19
        steps: 
              - uses: action/checkout@v4
              - name: installrpm
                run: | 
                    sudo yum -y install yum-utils
                    curl -o xyz.rpm ссылка
                    sudo yum install -y xyz.rpm
        
