name: CI
on: 
# События, которые запускают jobs
    commit_comment:
      branches: ["main"]
jobs:
# jobs запускаются параллельно, если не указана последовательность
    Cijob1:
        runs-on: ubuntu-latest
        container:
          image: node:18
          #run: cd~/Download/ #Ну по идее, так в докере работает
         # env:
           #   NODE_ENV: development
       #   ports:
       #       - 80
       #   volumes:
       #       - my_docker_volume:/volume_mount
      #    options: --cpus 1
        steps: 
             # -uses: Action/testing
            - name: installdeb
              run: #RUN cd ~/Download/ # По идее должен переходить в директорию, где установлен файл
                   RUN sudo dpkg -i file.dpb
                   RUN sudo apt-get -f install


    Cijob2:
        runs-on: oracle-latest
        container:
          image: node:19
        steps: 
             # -uses: Action/testing
            - name: installrpm
              run: RUN yum -y install yum-utils
                      RUN yum -y install python-setuptools
                      RUN yum install -y xyz.rpm
        
