name: CI
on: 
# События, которые запускают jobs
    commit_comment:
      branches: ["main"]
jobs:
# jobs запускаются параллельно, если не указана последовательность
    Cijob1:
        runs-on: ubuntu-latest
        container:
          image: node:18
         # env:
           #   NODE_ENV: development
       #   ports:
       #       - 80
       #   volumes:
       #       - my_docker_volume:/volume_mount
      #    options: --cpus 1
        steps: 
             # -uses: Action/testing
            - name: installdeb
              run: 
                   sudo dpkg -i file.dpb
                    sudo apt-get -f install


    Cijob2:
        runs-on: oracle-latest
        container:
          image: node:19
        steps: 
             # -uses: Action/testing
            - name: installrpm
              run:  sudo yum -y install yum-utils
                    sudo yum install -y xyz.rpm
        
